name: Build and Push Docker image

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Extract version from Dockerfile
      id: extract_version
      run: |
        VERSION=$(grep 'LABEL version=' Dockerfile | cut -d '"' -f2)
        echo "Extracted Version: $VERSION"
        echo "::set-output name=version::$VERSION"
      working-directory: /
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # Dies sollte auf das Wurzelverzeichnis des Repos zeigen
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fhb-assignment-backend:${{ steps.extract_version.outputs.version }}
      working-directory: /
