name: Node.js CI
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x.
      uses: actions/setup-node@v3
      with:
        node-version: 18.x.
    - name: Install dependencies
      run: npm install
    - name: Run test script
      run: npm run test
    - name: Run build script
      run: npm run build