name: Main workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  dependabot-workflow:
    uses: ./.github/workflows/dependabot.yaml
  nodejs-workflow:
    uses: ./.github/workflows/nodejs.yaml
  eslint-workflow:
    uses: ./.github/workflows/eslint.yaml
  docker-workflow:
    needs: nodejs-workflow
    uses: ./.github/workflows/docker.yaml
    secrets: inherit