name: Main workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  nodejs-workflow:
    uses: ./.github/workflows/nodejs.yaml
  eslint-workflow:
    uses: ./.github/workflows/eslint.yaml
  sonarcloud-workflow:
    uses: ./.github/workflows/sonarcloud.yml
    secrets: [ GITHUB_TOKEN, SONAR_TOKEN ]
  docker-workflow:
    needs: nodejs-workflow
    uses: ./.github/workflows/docker.yaml
    secrets: inherit